### ISSUE TITLE
Collab Summit Brainstorming / Docs / Learn

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7197]
triage / assess / breakout after the session

see also [learn content read out](https://nodejs.org/en/blog/events/collab-summit-2024-dublin#documentation-improvements-nodejs-learn-section)

---

- [x] created https://github.com/nodejs/learn/issues/33 
   - metadata on pages to tag last update
      - distinction between last reviewed and last updated 
   - flag when content gets stale
- [x] need more team accountability - not actionable
   - not a lot of folks want to write
   - we dont even get changelogs and release notes 
- [x] make sure the code is runnable - created https://github.com/nodejs/nodejs.org/issues/7293
- [x] frontmatter on learn pages tying to core apis - created https://github.com/nodejs/nodejs.org/issues/7294
- [x] [CODEOWNERS](https://github.com/nodejs/nodejs.org/blob/main/CODEOWNERS) improvements associated to teams related to the APIs highlighted in the learn content - created https://github.com/nodejs/nodejs.org/issues/7292
- [x] translation ?? we have trouble maintaining `en` today. taking no action on this. consensus at collab summit is we have low confidence we can do this. there is still chatter on crowdin about disappoint about this decision
- [x] we need information architecture work on the learn section | nodejs/learn#31
   - this is more like a graph than a linear path
   - can we point to courses or books or videos? pandoras box / conflict of interest 
   - node.js ambassadors / dev rel content
   - can we find technical writers to help
   - we should explore paying for this via open collective

**Comment by AugustinMauroy** [comment]
> [CODEOWNERS](https://github.com/nodejs/nodejs.org/blob/main/CODEOWNERS) improvements associated to teams related to the APIs highlighted in the learn content

- [test-runner](https://github.com/nodejs/nodejs.org/tree/main/apps/site/pages/en/learn/test-runner) should be under the test-runner team 
- [typescript](https://github.com/nodejs/nodejs.org/tree/main/apps/site/pages/en/learn/typescript) should be under typescript team 

_IMO_

> metadata on pages to tag last update

I'm more in favour of the version used in the example. Because a date has no value in relation to the runtime. In addition, having the version allows the contributor/collaborator to know if a document needs to be revised.
And from a functional point of view, I think we should add a bit to the `MetaBar` that allows you to install (redirect to the installation of the correct version).

> frontmatter on learn pages tying to core apis

I'd be more in favour of having an MDX component that puts the displayName and stability index linked to the version (idea above of having it in the frontmatter) and that also allows links on the page. 

> translation ?? we have trouble maintaining en today

I think we just have to note on the issue that talks about this that for the moment it's not a good idea because the content isn't ‘refined’ enough yet.

> this is more like a graph than a linear path

The ‘learning’ path must be a graph because node.js can be used for all sorts of things (CLI, http, automation, etc.). This means that you can't have a linear flow, you can't start with CLI then HTPP, nothing links them, they have to be run in parallel.

**Comment by bmuenzenmeyer** [comment]
closing this issue, all issues broken out for further triage.

thanks @AugustinMauroy for your initial thoughts
