### ISSUE TITLE
Expand CODEOWNERS to each learn section owner/advocate

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7292]
> Broken out of https://github.com/nodejs/nodejs.org/issues/7197
> Might be related to nodejs/learn#31

[CODEOWNERS](https://github.com/nodejs/nodejs.org/blob/main/CODEOWNERS) improvements associated to teams related to the APIs highlighted in the learn content

- [ ] Prerequisite https://github.com/nodejs/nodejs.org/issues/7294

for each identified api module / team:

- [ ] add a team, or expand access to `write` access if missing (CODEOWNERS must have write access)
- [ ] add the team and content paths to CODEOWNERS

**Comment by bmuenzenmeyer** [comment]
@AugustinMauroy identified these already

[test-runner](https://github.com/nodejs/nodejs.org/tree/main/apps/site/pages/en/learn/test-runner) should be under the test-runner team
[typescript](https://github.com/nodejs/nodejs.org/tree/main/apps/site/pages/en/learn/typescript) should be under typescript team

**Comment by AugustinMauroy** [comment]
Note that we can only take action on this when we have clearly defined the learning path/graph and each subsection is associated with one or two teams max.

**Comment by AugustinMauroy** [comment]
I've added it to the agenda to get their opinion on the matter.

**Comment by marco-ippolito** [comment]
No problem with adding @nodejs/typescript as codeowner of the typescript related content for review

**Comment by AugustinMauroy** [comment]
ping @nodejs/test_runner to move forward on this issue

**Comment by pmarchini** [comment]
Hey @AugustinMauroy, no problem for me regarding @nodejs/test_runner.
I'd suggest collecting some thoughts from @cjihrig, @MoLow, @atlowChemi, and @jakecastelli as well.

**Comment by JakobJingleheimer** [comment]
> ping [@nodejs/test_runner](https://github.com/orgs/nodejs/teams/test_runner) to move forward on this issue

I'm happy to do, although I'm not as active an implementer as Chemi, Colin, and Moshe.

**Comment by cjihrig** [comment]
I'm not quite sure what is being asked of me in this issue? I think using the test_runner team as CODEOWNERS is fine if that's the question. It's worth noting though that none of the subsystem specific teams actually represent expertise in that subsystem. It just means that those people have subscribed to notifications.

**Comment by AugustinMauroy** [comment]
> It just means that those people have subscribed to notifications.

And have to approve PRs

**Comment by pmarchini** [comment]
> > It just means that those people have subscribed to notifications.
> 
> And have to approve PRs

In Node Core, being part of the team does not grant any particular ownership.
It simply provides an easier way to manage notifications.
As far as I know, a team member's approval doesn't have any specific effect @AugustinMauroy.

**Comment by cjihrig** [comment]
Node core actually looked into leveraging CODEOWNERS years ago. That was exactly the problem though. Any collaborator can join any team and approve things... which defeats the whole purpose of CODEOWNERS.

**Comment by AugustinMauroy** [comment]
> Node core actually looked into leveraging CODEOWNERS years ago. That was exactly the problem though. Any collaborator can join any team and approve things... which defeats the whole purpose of CODEOWNERS.

That another question. IDK if there are a way to disable self joining team. **EDIT:** we cannot "join as it" we can request to join. IDK who approve that but there are a step before joining any team 

But for now we need someone that take care of nodejs learn content and it's why we use CODEOWNERS

**Comment by ovflowd** [comment]
That's not what @cjihrig meant, Augustin; Being added to a team might or might not require approval, but that's not the issue.

It is just that these people are not subject matter experts on these specific topics necessarily, but people that might be experts or not but that are interested in receiving notifications to PRs on Node.js Core related to said topics. Of course, the Node.js Bot pings said teams, but anyone can approve a PR (any collaborator) not exclusive to said team. There are cases of course where some PRs are requested either by some collaborators or the TSC to have an input from said "team".

I am still fine having this being the case for our CODEOWNERS, as we just want to notify that a change related to topic that touches said team is also being changed within the Website, and that might or might not be of interest of said "team".

**Comment by avivkeller** [comment]
In my view, the best approach comes down to one of two options:

**Option A:**
Add the relevant teams to the `CODEOWNERS` file *without* giving them write access. Then, like in the core repo, use a bot to ping those teams for the files they "own." This wouldn't require a CODEOWNER approving review unless the team has `write` access (i.e. TSC, Web, etc).

**Option B (My favorite):**
As suggested in nodejs/nodejs.org#7294, map each Learn article to a core API (e.g., `api: fs` in the frontmatter). GitHub Actions would then link each API to a specific team (e.g., `fs` → `@nodejs/fs`). A bot would ping the appropriate team based on the APIs mentioned in the article.

WDYT?

**Comment by AugustinMauroy** [comment]
> Option B:
As suggested in https://github.com/nodejs/nodejs.org/issues/7294, map each Learn article to a core API (e.g., api: fs in the frontmatter). GitHub Actions would then link each API to a specific team (e.g., fs → @nodejs/fs). A bot would ping the appropriate team based on the APIs mentioned in the article.

Not too bad idea. But what should we do for section that didn't have any specific topics/api

**Comment by avivkeller** [comment]
>  But what should we do for section that didn't have any specific topics/api

We'd cross that bridge when we get there. It would be the same situation if we used CODEOWNERS. Currently, the website team becomes the default editorial authority.

**Comment by AugustinMauroy** [comment]
> Currently, the website team becomes the default editorial authority.


what about a `@nodejs/website-content` ?

**Comment by ovflowd** [comment]
I'm strongly opposed with the CODE OWNERS approach and I'm firmly a -1 here. I don't understand why y'all are ignoring my suggestions of using nodes/node bot that pings the right teams without needing to change code owners and give write access to all these teams.

I'm fine removing my -1 if we all believe the code owners is truly the best approach.

**Comment by AugustinMauroy** [comment]
I agreed with you for the bot but it's didn't change the question about who we need to ping

**Comment by avivkeller** [comment]
> I'm strongly opposed with the CODE OWNERS approach and I'm firmly a -1 here. I don't understand why y'all are ignoring my suggestions of using nodes/node bot that pings the right teams without needing to change code owners and give write access to all these teams.
> 
> I'm fine removing my -1 if we all believe the code owners is truly the best approach.

That was my suggestion:

> Add the relevant teams to the CODEOWNERS file without giving them write access. Then, like in the core repo, use a bot to ping those teams for the files they "own."

> A bot would ping the appropriate team based on the APIs mentioned in the article.


I'm also a strong -1 on giving teams write access.

**Comment by ovflowd** [comment]
> Add the relevant teams to the CODEOWNERS file without giving them write access. Then, like in the core repo, use a bot to ping those teams for the files they "own."

Oh I misread lol 😅
